package ru.pimpay.platform.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-04-23T18:39:21.726+03:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "PlatformApiService", 
                  wsdlLocation = "file:src/main/resources/wsdl/PlatformApiWsdl.wsdl",
                  targetNamespace = "urn:PlatformApiWsdl") 
public class PlatformApiService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:PlatformApiWsdl", "PlatformApiService");
    public final static QName PlatformApiPort = new QName("urn:PlatformApiWsdl", "PlatformApiPort");
    static {
        URL url = null;
        try {
            url = new URL("file:src/main/resources/wsdl/PlatformApiWsdl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PlatformApiService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:src/main/resources/wsdl/PlatformApiWsdl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PlatformApiService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PlatformApiService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PlatformApiService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PlatformApiService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PlatformApiService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PlatformApiService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns PlatformApiPortType
     */
    @WebEndpoint(name = "PlatformApiPort")
    public PlatformApiPortType getPlatformApiPort() {
        return super.getPort(PlatformApiPort, PlatformApiPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PlatformApiPortType
     */
    @WebEndpoint(name = "PlatformApiPort")
    public PlatformApiPortType getPlatformApiPort(WebServiceFeature... features) {
        return super.getPort(PlatformApiPort, PlatformApiPortType.class, features);
    }

}
